# nginx 端口转发
stream {
    upstream mysqlSocket {
       hash $remote_addr consistent;
       server yourIp:3306 weight=5 max_fails=3 fail_timeout=30s;
    }

    upstream nacosSocket {
       hash $remote_addr consistent;
       server 127.0.0.1:8080 weight=5 max_fails=3 fail_timeout=30s;
    }
    server {
        listen 20998;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass mysqlSocket;
        allow 61.133.217.141;
        deny all;
    }


    server {
        listen 20997;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass nacosSocket;
        allow 61.133.217.141;
        deny all;
    }
}



